const GET_TABS_ASYNC = 'GET_TABS_ASYNC'
const GET_TABS_SUCCESS = 'GET_TABS_SUCCESS'
const GET_TABS_ERROR = 'GET_TABS_ERROR'

const SET_SELECTED_TAB_ASYNC = 'SET_SELECTED_TAB_ASYNC'
const GET_TAB_CONTENT_SUCCESS = 'GET_TAB_CONTENT_SUCCESS'
const GET_TAB_CONTENT_ERROR = 'GET_TAB_CONTENT_ERROR'

const SELECT_FONT = 'SELECT_FONT'

const types = {
  GET_TABS_ASYNC,
  GET_TABS_SUCCESS,
  GET_TABS_ERROR,

  SET_SELECTED_TAB_ASYNC,
  GET_TAB_CONTENT_SUCCESS,
  GET_TAB_CONTENT_ERROR,

  SELECT_FONT
}

export default types
